"""add_cluster_id_and_duplicate_to_scans

Revision ID: b987dce6a5ac
Revises: dbd114688fad
Create Date: 2026-09-22 00:35:28.726418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b987dce6a5ac'
down_revision: Union[str, Sequence[str], None] = 'dbd114688fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consistency_checks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('check_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('observed_values', sa.JSON(), nullable=True),
    sa.Column('calculated_value', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_checks_check_type'), 'consistency_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_consistency_checks_status'), 'consistency_checks', ['status'], unique=False)
    op.add_column('extracted_fields', sa.Column('evidence_state', sa.String(), nullable=True))
    op.add_column('extracted_fields', sa.Column('quality_reasons', sa.JSON(), nullable=True))
    op.add_column('product_clusters', sa.Column('gtin', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('product_name', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('variant', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('net_quantity', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('match_method', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('match_strength', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('priority_class', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('priority_reasons', sa.JSON(), nullable=True))
    op.add_column('product_clusters', sa.Column('evidence_strength', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('actionability_state', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('prioritization_version', sa.String(), nullable=True))
    op.add_column('product_clusters', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('product_clusters', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_product_clusters_gtin'), 'product_clusters', ['gtin'], unique=False)
    op.drop_column('product_clusters', 'issue_type')
    op.add_column('rule_results', sa.Column('applicability', sa.String(), nullable=False))
    op.add_column('scans', sa.Column('cluster_id', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('duplicate_of_scan_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scans', 'product_clusters', ['cluster_id'], ['id'])
    op.create_foreign_key(None, 'scans', 'scans', ['duplicate_of_scan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.drop_column('scans', 'duplicate_of_scan_id')
    op.drop_column('scans', 'cluster_id')
    op.drop_column('rule_results', 'applicability')
    op.add_column('product_clusters', sa.Column('issue_type', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_product_clusters_gtin'), table_name='product_clusters')
    op.alter_column('product_clusters', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('product_clusters', 'created_at')
    op.drop_column('product_clusters', 'prioritization_version')
    op.drop_column('product_clusters', 'actionability_state')
    op.drop_column('product_clusters', 'evidence_strength')
    op.drop_column('product_clusters', 'priority_reasons')
    op.drop_column('product_clusters', 'priority_class')
    op.drop_column('product_clusters', 'match_strength')
    op.drop_column('product_clusters', 'match_method')
    op.drop_column('product_clusters', 'net_quantity')
    op.drop_column('product_clusters', 'variant')
    op.drop_column('product_clusters', 'product_name')
    op.drop_column('product_clusters', 'brand')
    op.drop_column('product_clusters', 'gtin')
    op.drop_column('extracted_fields', 'quality_reasons')
    op.drop_column('extracted_fields', 'evidence_state')
    op.drop_index(op.f('ix_consistency_checks_status'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_check_type'), table_name='consistency_checks')
    op.drop_table('consistency_checks')
    # ### end Alembic commands ###
