"""
scripts/seed_demo_data.py
─────────────────────────────────────────────────────────────────────────────
LM-Screen SIH Demonstration Data Seeder

PURPOSE: Creates 8 deterministic, clearly synthetic demo scenarios for the
SIH evaluation presentation. All records are tagged is_demo=True (via
demo_tag field) so they can be cleanly separated from real data.

[!]  IMPORTANT DISCLAIMER:
    All data generated by this script is SYNTHETIC and FABRICATED for
    demonstration purposes ONLY. It does NOT represent:
    - Real citizen submissions
    - Real product compliance measurements
    - Real inspection outcomes
    - Real Legal Metrology enforcement actions

Run:
    python scripts/seed_demo_data.py

Safe to run multiple times — idempotent (checks before inserting).

Reset:
    python scripts/reset_demo_data.py
"""

import sys
import os
import datetime

# Allow running from project root
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from backend.app.database import engine, Base, SessionLocal
from backend.app.models.models import (
    User, Product, Scan, ExtractedField, RuleResult,
    CitizenReport, ProductCluster, OfficerReview, DecisionTrace
)

DEMO_TAG = "SIH_DEMO_SYNTHETIC"  # All demo records carry this identifier


def _tag(field: str) -> str:
    return f"[DEMO] {field}"


def seed_demo_data():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    created = 0

    try:
        # ── Demo Users ─────────────────────────────────────────────────────────
        officer = db.query(User).filter(User.email == "officer@legalmetrology.gov.in").first()
        if not officer:
            officer = User(
                email="officer@legalmetrology.gov.in",
                hashed_password="DEMO_HASH_NOT_REAL",
                full_name="Inspector R. K. Sharma (DEMO)",
                role="OFFICER",
                badge_number="LM-DEMO-1001"
            )
            db.add(officer)
            db.flush()
            created += 1

        citizen = db.query(User).filter(User.email == "citizen.demo@example.com").first()
        if not citizen:
            citizen = User(
                email="citizen.demo@example.com",
                hashed_password="DEMO_HASH_NOT_REAL",
                full_name="Demo Citizen (SYNTHETIC)",
                role="CITIZEN"
            )
            db.add(citizen)
            db.flush()
            created += 1

        db.commit()

        # ──────────────────────────────────────────────────────────────────────
        # SCENARIO 1 — Clean Readable Product (PASS_SCREENING)
        # ──────────────────────────────────────────────────────────────────────
        p1 = db.query(Product).filter(Product.gtin == "DEMO-8901111111111").first()
        if not p1:
            p1 = Product(
                gtin="DEMO-8901111111111",
                brand_name="PureHarvest [DEMO]",
                product_name="Organic Wheat Atta 5kg [DEMO]",
                manufacturer="PureHarvest Agro Foods Pvt Ltd [SYNTHETIC]",
                category="food"
            )
            db.add(p1)
            db.flush()

            s1 = Scan(
                product_id=p1.id,
                image_hash=f"{DEMO_TAG}_scenario1_clean_atta",
                image_path="uploads/demo_placeholder.png",
                quality_status="ACCEPTABLE",
                blur_score=145.2,
                brightness_score=0.56,
                glare_ratio=0.02,
                status="PASS_SCREENING",
                public_label="No issue detected in the checks performed",
                screening_confidence=0.94,
                rule_version="2026.1"
            )
            db.add(s1)
            db.flush()

            for fname, raw, norm, conf, method in [
                ("mrp", "MRP Rs. 260.00", "₹ 260.00", 0.96, "REGEX_PATTERN"),
                ("net_quantity", "Net Qty: 5.0 kg", "5 kg", 0.95, "REGEX_PATTERN"),
                ("manufacture_date", "MFD: 01/2026", "01/2026", 0.92, "KEYWORD_ANCHOR"),
                ("manufacturer_or_packer", "PureHarvest Agro Foods [DEMO]", "PureHarvest Agro Foods [DEMO]", 0.90, "KEYWORD_ANCHOR"),
                ("consumer_care", "Consumer Care: 1800-11-0001 [DEMO]", "1800-11-0001", 0.93, "KEYWORD_ANCHOR"),
            ]:
                db.add(ExtractedField(scan_id=s1.id, field_name=fname, raw_value=raw, normalized_value=norm,
                                     confidence=conf, extraction_method=method, evidence_state="SUPPORTED"))

            for rid, rname, rstatus, rreason in [
                ("LM001", "MRP Screening", "PASS", "[DEMO] MRP declaration present and correctly formatted."),
                ("LM002", "Net Quantity Screening", "PASS", "[DEMO] Net quantity visible in metric units."),
                ("LM003", "Manufacture Date", "PASS", "[DEMO] Month/Year of manufacture visible."),
            ]:
                db.add(RuleResult(scan_id=s1.id, rule_id=rid, rule_name=rname, status=rstatus, reason=rreason, confidence=0.94))

            db.commit()
            created += 1
            print("[OK] Scenario 1: Clean product (PASS_SCREENING) — created")

        # ──────────────────────────────────────────────────────────────────────
        # SCENARIO 2 — Missing MRP (POTENTIAL_NON_COMPLIANCE)
        # ──────────────────────────────────────────────────────────────────────
        p2 = db.query(Product).filter(Product.gtin == "DEMO-8902222222222").first()
        if not p2:
            p2 = Product(
                gtin="DEMO-8902222222222",
                brand_name="ChocoDelight [DEMO]",
                product_name="Dark Chocolate Bar 100g [DEMO]",
                manufacturer="ChocoDelight Confectionery [SYNTHETIC]",
                category="food"
            )
            db.add(p2)
            db.flush()

            s2 = Scan(
                product_id=p2.id,
                image_hash=f"{DEMO_TAG}_scenario2_missing_mrp",
                image_path="uploads/demo_placeholder.png",
                quality_status="ACCEPTABLE",
                blur_score=118.0,
                brightness_score=0.48,
                glare_ratio=0.04,
                status="POTENTIAL_NON_COMPLIANCE",
                public_label="Potential non-compliance detected",
                screening_confidence=0.88,
                rule_version="2026.1"
            )
            db.add(s2)
            db.flush()

            for fname, raw, norm, conf, method in [
                ("net_quantity", "Net Wt: 100g", "100 g", 0.94, "REGEX_PATTERN"),
                ("manufacture_date", "MFD: 02/2026", "02/2026", 0.91, "KEYWORD_ANCHOR"),
            ]:
                db.add(ExtractedField(scan_id=s2.id, field_name=fname, raw_value=raw, normalized_value=norm,
                                     confidence=conf, extraction_method=method, evidence_state="SUPPORTED"))

            db.add(RuleResult(scan_id=s2.id, rule_id="LM001", rule_name="MRP Screening",
                              status="POTENTIAL_NON_COMPLIANCE",
                              reason="[DEMO] Required statutory declaration 'mrp' not detected in visible label panel.",
                              confidence=0.88))
            db.add(RuleResult(scan_id=s2.id, rule_id="LM002", rule_name="Net Quantity Screening",
                              status="PASS", reason="[DEMO] Net quantity visible.", confidence=0.94))

            cluster2 = ProductCluster(
                product_id=p2.id,
                report_count=3,
                ai_flag_count=2,
                priority_score=0.78,
                priority_class="PRIORITY_REVIEW",
                status="REVIEW_REQUIRED"
            )
            db.add(cluster2)
            db.flush()

            db.add(CitizenReport(
                product_id=p2.id, scan_id=s2.id,
                reporter_hash="DEMO_citizen_hash_001",
                issue_category="Missing Information [DEMO]",
                description="[DEMO SYNTHETIC] MRP sticker missing from back panel.",
                location_city="Mumbai [DEMO]",
                status="UNVERIFIED"
            ))
            db.commit()
            created += 1
            print("[OK] Scenario 2: Missing MRP (POTENTIAL_NON_COMPLIANCE) — created")

        # ──────────────────────────────────────────────────────────────────────
        # SCENARIO 3 — Poor Image Quality (NEEDS_REVIEW)
        # ──────────────────────────────────────────────────────────────────────
        p3 = db.query(Product).filter(Product.gtin == "DEMO-8903333333333").first()
        if not p3:
            p3 = Product(
                gtin="DEMO-8903333333333",
                brand_name="DailyFresh [DEMO]",
                product_name="Skimmed Milk Powder 200g [DEMO]",
                manufacturer="DailyFresh Dairy Products [SYNTHETIC]",
                category="food"
            )
            db.add(p3)
            db.flush()

            s3 = Scan(
                product_id=p3.id,
                image_hash=f"{DEMO_TAG}_scenario3_blurry",
                image_path="uploads/demo_placeholder.png",
                quality_status="RETAKE_REQUIRED",
                blur_score=12.4,
                brightness_score=0.18,
                glare_ratio=0.32,
                status="NEEDS_REVIEW",
                public_label="More evidence or human review required",
                screening_confidence=0.35,
                rule_version="2026.1"
            )
            db.add(s3)
            db.flush()

            db.add(DecisionTrace(
                scan_id=s3.id, stage="IMAGE_QUALITY",
                output_summary={"status": "RETAKE_REQUIRED",
                                "detail": "[DEMO] Blur score 12.4 below threshold. Image not suitable for reliable evidence extraction."}
            ))
            db.commit()
            created += 1
            print("[OK] Scenario 3: Poor image quality (NEEDS_REVIEW) — created")

        # ──────────────────────────────────────────────────────────────────────
        # SCENARIO 4 — Barcode/OCR Mismatch (NEEDS_REVIEW + consistency flag)
        # ──────────────────────────────────────────────────────────────────────
        p4 = db.query(Product).filter(Product.gtin == "DEMO-8904444444444").first()
        if not p4:
            p4 = Product(
                gtin="DEMO-8904444444444",
                brand_name="HealthPlus [DEMO]",
                product_name="Oats Porridge Mix 500g [DEMO]",
                manufacturer="HealthPlus Nutrition [SYNTHETIC]",
                category="food"
            )
            db.add(p4)
            db.flush()

            s4 = Scan(
                product_id=p4.id,
                image_hash=f"{DEMO_TAG}_scenario4_barcode_mismatch",
                image_path="uploads/demo_placeholder.png",
                quality_status="ACCEPTABLE",
                blur_score=130.0,
                brightness_score=0.52,
                glare_ratio=0.03,
                status="NEEDS_REVIEW",
                public_label="More evidence or human review required",
                screening_confidence=0.62,
                rule_version="2026.1"
            )
            db.add(s4)
            db.flush()

            # OCR finds one GTIN, barcode scanner finds another -> consistency conflict
            for fname, raw, norm, conf, method, estate in [
                ("gtin", "8904444444444", "DEMO-8904444444444", 0.78, "OCR_BARCODE_REGION", "CONFLICTING"),
                ("mrp", "MRP Rs. 120.00", "₹ 120.00", 0.90, "REGEX_PATTERN", "SUPPORTED"),
                ("net_quantity", "500g", "500 g", 0.88, "REGEX_PATTERN", "SUPPORTED"),
            ]:
                db.add(ExtractedField(scan_id=s4.id, field_name=fname, raw_value=raw, normalized_value=norm,
                                     confidence=conf, extraction_method=method, evidence_state=estate,
                                     quality_reasons=["[DEMO] Barcode scan returned different GTIN than OCR region"]))

            db.commit()
            created += 1
            print("[OK] Scenario 4: Barcode/OCR GTIN mismatch (NEEDS_REVIEW + CONFLICTING evidence) — created")

        # ──────────────────────────────────────────────────────────────────────
        # SCENARIO 5 — Multiple Citizen Observations (high-priority cluster)
        # ──────────────────────────────────────────────────────────────────────
        p5 = db.query(Product).filter(Product.gtin == "DEMO-8905555555555").first()
        if not p5:
            p5 = Product(
                gtin="DEMO-8905555555555",
                brand_name="FastBites [DEMO]",
                product_name="Instant Noodles Masala 75g [DEMO]",
                manufacturer="FastBites Foods India Ltd [SYNTHETIC]",
                category="food"
            )
            db.add(p5)
            db.flush()

            cluster5 = ProductCluster(
                product_id=p5.id,
                report_count=8,
                ai_flag_count=3,
                priority_score=0.89,
                priority_class="PRIORITY_REVIEW",
                status="REVIEW_REQUIRED",
                priority_reasons=[
                    "[DEMO] 8 citizen signals received from 6 cities",
                    "[DEMO] 3 system flags: MRP discrepancy",
                    "[DEMO] Pattern: Multiple price stickers observed"
                ]
            )
            db.add(cluster5)
            db.flush()

            cities = ["Delhi", "Mumbai", "Pune", "Bengaluru", "Chennai", "Hyderabad", "Kolkata", "Jaipur"]
            descs = [
                "[DEMO] MRP label printed over original price",
                "[DEMO] Two different MRP prices on same pack",
                "[DEMO] MRP higher than earlier batch",
                "[DEMO] Retailer charging above printed MRP",
                "[DEMO] MRP sticker applied on top of another",
                "[DEMO] Pack says Rs. 20 but sold at Rs. 25",
                "[DEMO] MRP partially scratched off",
                "[DEMO] Different MRP on front vs back"
            ]
            for i in range(8):
                db.add(CitizenReport(
                    product_id=p5.id,
                    reporter_hash=f"DEMO_citizen_hash_noodles_{i+1:02d}",
                    issue_category="Suspicious MRP [DEMO]",
                    description=descs[i],
                    location_city=f"{cities[i]} [DEMO]",
                    status="UNVERIFIED",
                    created_at=datetime.datetime.utcnow() - datetime.timedelta(days=i)
                ))
            db.commit()
            created += 1
            print("[OK] Scenario 5: Citizen cluster (8 signals, PRIORITY_REVIEW) — created")

        # ──────────────────────────────────────────────────────────────────────
        # SCENARIO 6 — Officer Correction Demo
        # ──────────────────────────────────────────────────────────────────────
        p6 = db.query(Product).filter(Product.gtin == "DEMO-8906666666666").first()
        if not p6:
            p6 = Product(
                gtin="DEMO-8906666666666",
                brand_name="GrainWell [DEMO]",
                product_name="Brown Rice 1kg [DEMO]",
                manufacturer="GrainWell Agro [SYNTHETIC]",
                category="food"
            )
            db.add(p6)
            db.flush()

            s6 = Scan(
                product_id=p6.id,
                image_hash=f"{DEMO_TAG}_scenario6_officer_correction",
                image_path="uploads/demo_placeholder.png",
                quality_status="ACCEPTABLE",
                blur_score=138.0,
                brightness_score=0.53,
                glare_ratio=0.02,
                status="POTENTIAL_NON_COMPLIANCE",
                public_label="Potential non-compliance detected",
                screening_confidence=0.80,
                rule_version="2026.1"
            )
            db.add(s6)
            db.flush()

            # OCR misread the MRP value
            ev6 = ExtractedField(
                scan_id=s6.id, field_name="mrp",
                raw_value="MRP Rs. 8O.00",  # '8O' — 'O' instead of '0' (OCR error)
                normalized_value="Rs. 80.00 [OCR uncertain]",
                confidence=0.61,
                extraction_method="REGEX_PATTERN",
                evidence_state="UNCERTAIN",
                quality_reasons=["[DEMO] OCR confidence below threshold; character '0' vs 'O' ambiguity detected"]
            )
            db.add(ev6)
            db.flush()

            # Officer corrects it
            db.add(DecisionTrace(
                scan_id=s6.id,
                stage="OFFICER_CORRECTION",
                output_summary={
                    "status": "MANUALLY_VERIFIED",
                    "detail": "[DEMO] Officer Inspector Sharma corrected MRP from 'Rs. 80.00 [OCR uncertain]' to '₹ 80.00' after physical inspection."
                }
            ))

            cluster6 = ProductCluster(
                product_id=p6.id,
                report_count=1,
                ai_flag_count=1,
                priority_score=0.55,
                priority_class="STANDARD_REVIEW",
                status="OFFICER_REVIEWED"
            )
            db.add(cluster6)
            db.flush()

            db.add(OfficerReview(
                cluster_id=cluster6.id,
                scan_id=s6.id,
                officer_id=officer.id,
                decision="OFFICER_REVIEWED",
                rationale="[DEMO] Physical inspection confirmed MRP is ₹80.00. OCR misread '0' as 'O'. Evidence corrected.",
                previous_status="POTENTIAL_NON_COMPLIANCE",
                new_status="OFFICER_REVIEWED"
            ))
            db.commit()
            created += 1
            print("[OK] Scenario 6: Officer correction (OCR uncertainty -> MANUALLY_VERIFIED) — created")

        # ──────────────────────────────────────────────────────────────────────
        # SCENARIO 7 — Unknown Product Context (CONTEXT_REVIEW)
        # ──────────────────────────────────────────────────────────────────────
        p7 = db.query(Product).filter(Product.gtin == "DEMO-8907777777777").first()
        if not p7:
            p7 = Product(
                gtin="DEMO-8907777777777",
                brand_name="Unknown Brand [DEMO]",
                product_name="Unclassified Commodity [DEMO]",
                manufacturer="Unknown Manufacturer [SYNTHETIC]",
                category="unknown"
            )
            db.add(p7)
            db.flush()

            s7 = Scan(
                product_id=p7.id,
                image_hash=f"{DEMO_TAG}_scenario7_unknown_context",
                image_path="uploads/demo_placeholder.png",
                quality_status="ACCEPTABLE",
                blur_score=135.0,
                brightness_score=0.50,
                glare_ratio=0.05,
                status="NEEDS_REVIEW",
                public_label="More evidence or human review required",
                screening_confidence=0.45,
                rule_version="2026.1",
                category="unknown"
            )
            db.add(s7)
            db.flush()

            db.add(DecisionTrace(
                scan_id=s7.id,
                stage="PRODUCT_CLASSIFICATION",
                output_summary={
                    "status": "CONTEXT_REVIEW_REQUIRED",
                    "detail": "[DEMO] Product category could not be determined from OCR tokens. Conditional rules not activated."
                }
            ))
            db.commit()
            created += 1
            print("[OK] Scenario 7: Unknown context (CONTEXT_REVIEW_REQUIRED) — created")

        # ──────────────────────────────────────────────────────────────────────
        # SCENARIO 8 — Duplicate Image Submission
        # ──────────────────────────────────────────────────────────────────────
        p8 = db.query(Product).filter(Product.gtin == "DEMO-8901111111111").first()
        # Reuse product 1 (same product, duplicate scan)
        if p8:
            existing_dup = db.query(Scan).filter(
                Scan.image_hash == f"{DEMO_TAG}_scenario8_duplicate"
            ).first()
            if not existing_dup:
                s8 = Scan(
                    product_id=p8.id,
                    image_hash=f"{DEMO_TAG}_scenario8_duplicate",
                    image_path="uploads/demo_placeholder.png",
                    quality_status="ACCEPTABLE",
                    blur_score=145.2,
                    brightness_score=0.56,
                    glare_ratio=0.02,
                    status="PASS_SCREENING",
                    public_label="No issue detected in the checks performed",
                    screening_confidence=0.94,
                    rule_version="2026.1",
                    duplicate_of_scan_id=None  # Set to scenario 1's scan_id in a real deployment
                )
                db.add(s8)
                db.flush()

                db.add(DecisionTrace(
                    scan_id=s8.id,
                    stage="DUPLICATE_DETECTION",
                    output_summary={
                        "status": "DUPLICATE_OBSERVATION",
                        "detail": "[DEMO] Image hash matches a previous submission for this product. Original scan preserved."
                    }
                ))
                db.commit()
                created += 1
                print("[OK] Scenario 8: Duplicate image (DUPLICATE_OBSERVATION, original preserved) — created")

        print(f"\n{'='*60}")
        print(f"SIH DEMO DATA SEEDING COMPLETE")
        print(f"Records created this run: {created}")
        print(f"All records tagged: {DEMO_TAG}")
        print(f"\n[!]  DISCLAIMER: All data above is SYNTHETIC and FABRICATED")
        print(f"   for SIH demonstration purposes ONLY.")
        print(f"   It does NOT represent real citizen activity,")
        print(f"   real products, or real compliance measurements.")
        print(f"{'='*60}")

    finally:
        db.close()


if __name__ == "__main__":
    seed_demo_data()
